name: turnoapp
description: Turno - Coordinacion de turnos universitarios
publish_to: "none"
version: 1.0.1+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1

  # Supabase
  supabase_flutter: ^2.5.0

  # Navigation
  go_router: ^13.2.0

  # UI
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.3.0
  app_links: ^7.0.0
  webview_flutter: ^4.8.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.2.3

  # Monitoring
  sentry_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
